// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © cdikici71
// thanks to Rashid
//@version=5
indicator("cd_sweep&cisd_Cx",overlay=true,max_boxes_count = 500,max_lines_count = 100)
htf_opt     = input.string(defval ="Auto", title="HTF Selection method:",options=["Auto","Fixed"],group ="HTF",inline="htf0")
htf_        = input.timeframe(defval= "60", title = "If Fixed HTF:",group ="HTF",inline="htf")
showhtf     = input.bool(defval = true,title = "Show HTF boxes",group="HTF",inline="htf1")
width_box   = input.int(defval=1,title="Border Width :",group="HTF",inline= "htf1")
style_box   = input.string(defval=line.style_dotted,title= "Style:",options=[line.style_solid,line.style_dotted,line.style_dashed ],group="HTF",inline= "htf1")
indalert    = input.bool(defval = true,title = "Use indicator alerts",group="HTF",inline="al",tooltip = "When using the TradingView alert feature, it should be inactive.")
looksmt     = input.bool(defval = true,title = "Show SMT",group="HTF",inline="smt")
show_candle = input.bool(defval = true,title = "Show HTF Candle",group="HTF",inline="htf2")
show_rm     = input.bool(defval = true,title = "Show Remaining Time",group="HTF",inline="htf3") // new 2608
dx          = input(defval= 0 ,title = " Start from ahead",group="HTF",inline="htf4")
//////////////////////////
htfbias = input.timeframe(defval= "60", title = "HTF for bias",group ="BIAS")
plotbias= input.bool(defval = false,title='Plot Htf Bias',group ="BIAS" )
/////////////////
bull_color   = input.color(defval = color.teal, title=" Bull Color " , inline="clr", group= "Colors")
bear_color   = input.color(defval = color.red, title=" Bear Color " , inline="clr", group= "Colors")
range_color  = input.color(defval=color.navy,title= "Range Color",inline="clr",group="Colors")
swept_color  = input.color(defval= #ffeb3b32 ,title= "Sweep Box Color",inline="clr1",group="Colors")
key_txtcolor = input.color(defval= color.new(color.red,0),title= "Key Levels Text Color     ",inline="clr1",group="Colors")
can_br_color = input.color(defval= color.black ,title= "Candles Border Color",inline="clr2",group="Colors")
csd_color    = input.color(defval= color.navy ,title= "Cisd Line Color",inline="clr2",group="Colors")
show_keylvl  = input.bool(defval=true,title="Show Key Levels",group="Time Frames => Key Levels",inline= "key")
ky           = input(defval= 20 ,title = " Start from ahead",group="Time Frames => Key Levels",inline="key")

showkeytf1  = input.bool(defval =true , title = "",group ="Time Frames => Key Levels",inline="key1") 
showkeytf2  = input.bool(defval =true , title = "",group ="Time Frames => Key Levels",inline="key2")
showkeytf3  = input.bool(defval =true , title = "",group ="Time Frames => Key Levels",inline="key3") 


keytf1      = input.timeframe(defval= "1M",  title = "Tf1 :",group= "Time Frames => Key Levels",inline="key1")
keytf2      = input.timeframe(defval= "1W",  title = "Tf2 :",group= "Time Frames => Key Levels",inline="key2")
keytf3      = input.timeframe(defval= "1D",  title = "Tf3 :",group= "Time Frames => Key Levels",inline="key3")


keytf1_clr  = input.color(defval = color.gray, title="",group ="Time Frames => Key Levels",inline="key1")
keytf2_clr  = input.color(defval = color.gray, title="",group ="Time Frames => Key Levels",inline="key2")
keytf3_clr  = input.color(defval = color.gray, title="",group ="Time Frames => Key Levels",inline="key3")


//////////////////
show_cisd=input.bool(defval= true , title= "Show CISD table",group="Table")
//Turn Table On/Off
tableOn = input.bool(true, title="HTF Swept Table ", group="Table")
//Table Location & Size
i_font     = input.string("small", "Text size",  options = ["tiny", "small",  "normal", "large", "huge"], group = "Table")
i_pos      = input.string(position.middle_right, "Table Position", inline  = "1", options = [position.middle_right, position.top_right,position.bottom_right,position.bottom_center], group = "Table")

i_bgcolor  = color.teal
i_textcolor= color.white
/////
sym = syminfo.tickerid 
tf = timeframe.period

///////////////////////////////////
f_look_tf(_tf)=>
    dtf = 
     _tf == "1D"  ? "5" :
     _tf == "2D"  ? "5" :    
     _tf == "3D"  ? "5" :
     _tf == "4D"  ? "5" :
     _tf == "5D"  ? "5" :
     _tf == "6D"  ? "5" :
     _tf == "7D"  ? "5" :
     _tf == "8D"  ? "5" :
     _tf == "9D"  ? "5" :
     _tf == "10D" ? "5" :
     _tf == "11D" ? "5" :
     _tf == "12D" ? "5" :
     _tf == "13D" ? "5" :
     _tf == "14D" ? "5" :
     _tf == "15D" ? "5" :
     _tf == "16D" ? "5" :
     _tf == "17D" ? "5" :
     _tf == "19D" ? "5" :
     _tf == "20D" ? "5" :
     _tf == "21D" ? "5" :
     _tf == "23D" ? "5" :
     _tf == "25D" ? "5" :
     _tf == "28D" ? "5" :
     _tf == "31D" ? "5" :
     _tf == "33D" ? "5" :
     _tf == "34D" ? "5" :
     _tf == "37D" ? "5" :
     _tf == "40D" ? "5" :
     _tf == "43D" ? "5" :
     _tf == "45D" ? "5" :
     _tf == "46D" ? "5" :
     _tf == "49D" ? "5" :
     _tf == "53D" ? "5" :
     _tf == "55D" ? "5" :
     _tf == "57D" ? "5" :
     _tf == "59D" ? "5" :
     _tf == "61D" ? "5" :
     _tf == "65D" ? "5" :
     _tf == "69D" ? "5" :
     _tf == "73D" ? "5" :
     _tf == "77D" ? "5" :
     _tf == "81D" ? "5" :
     _tf == "86D" ? "5" :
     _tf == "89D" ? "5" :
     _tf == "91D" ? "5" :
     _tf == "96D" ? "5" :
     _tf == "101D" ? "5" :
     _tf == "106D" ? "5" :
     _tf == "111D" ? "5" :
     _tf == "116D" ? "5" :
     _tf == "121D" ? "5" :
     _tf == "127D" ? "5" :
     _tf == "133D" ? "5" :
     _tf == "139D" ? "5" :
     _tf == "144D" ? "5" :
     _tf == "145D" ? "5" :
     _tf == "151D" ? "5" :
     _tf == "157D" ? "5" :
     _tf == "163D" ? "5" :
     _tf == "169D" ? "5" :
     _tf == "176D" ? "5" :
     _tf == "183D" ? "5" :
     _tf == "190D" ? "5" :
     _tf == "197D" ? "5" :
     _tf == "204D" ? "5" :
     _tf == "211D" ? "5" :
     _tf == "218D" ? "5" :
     _tf == "225D" ? "5" :
     _tf == "233D" ? "5" :
     _tf == "241D" ? "5" :
     _tf == "249D" ? "5" :
     _tf == "257D" ? "5" :
     _tf == "265D" ? "5" :
     _tf == "273D" ? "5" :
     _tf == "281D" ? "5" :
     _tf == "289D" ? "5" :
     _tf == "298D" ? "5" :
     _tf == "307D" ? "5" :
     _tf == "316D" ? "5" :
     _tf == "325D" ? "5" :
     _tf == "334D" ? "5" :
     _tf == "343D" ? "5" :
     _tf == "352D" ? "5" :
     _tf == "361D" ? "5" : tf
    dtf

htf = htf_opt == "Auto" ? f_look_tf(tf) : htf_         
///////////////////////////////     
var o0 = open
var h0 = high
var l0 = low
var h0bar = bar_index
var l0bar = bar_index
var h1bar = bar_index
var l1bar = bar_index
var h0t   = time
var l0t   = time
var t0 = time
var c0 = close
var h1 = high
var l1 = low
var t1 = time
var c1 = close
var o1 = open
var h2 = high
var l2 = low
var o2 = open
var c2 = close
var h3 = high
var l3 = low
var o3 = open
var c3 = close
var h_swept1 = false
var l_swept1 = false
if timeframe.change(htf)
    t0 := time
    o0 := open
    h0 := high
    l0 := low
if high >= h0
    h0 := high
    h0bar := bar_index
    h0t   := time    
if low <= l0
    l0 := low
    l0bar := bar_index
    l0t   := time
c0:= close
if timeframe.change(htf)
    o1 := o0[1]
    h1 := h0[1]
    l1 := l0[1]
    t1 := t0[1]
    c1 := close[1] 
    h2 := h1[1]
    l2 := l1[1]
    o2 := o1[1]
    c2 := c1[1]
    h3 := h2[1]
    l3 := l2[1]
    o3 := o2[1]
    c3 := c2[1]

    l1bar := l0bar[1]
    h1bar := h0bar[1]
f_hswept(_sym,_tf)=>

    if h0 > h1 and math.max(o0,c0) <= h1 
        _h_swept = true    

f_lswept(_sym,_tf)=>

    if l0 < l1 and math.min(o0,c0) >= l1 
        _l_swept = true    
f_text(string _tf)=>
    _text = str.tonumber(_tf) < 59 ? _tf + 'm'  :
     str.tonumber(_tf) > 59  ? 'h'+ str.tostring(math.floor(str.tonumber(_tf)/60))    : _tf
    _text := _tf == "1D" ? "D" : _tf == "1W" ? "W" : _tf == "1M" ? "M" : _text

f_tfcon(_tf)=>
    timeframe.in_seconds(_tf) / 60 >= timeframe.in_seconds(timeframe.period)/60

Getcolor(_sym,res, data1, i1 , data2,i2) =>
    [op,cl] = request.security(_sym, res, [data1[i1],data2[i2]], lookahead=barmerge.lookahead_on ,ignore_invalid_symbol = true)
    clr = op > cl ? color.new(bear_color, 0) : color.new(bull_color,0)
    clr
add_to_array(arr, value) =>
    array.unshift(arr, value)
    if array.size(arr) > 100
        array.pop(arr)
tf_ok(_htf) =>
    _ok = tf == _htf or (timeframe.in_seconds(_htf) >= timeframe.in_seconds(timeframe.period)) or (str.tonumber(_htf) >= str.tonumber(timeframe.period)) or 
     (_htf == "1D" and str.tonumber(timeframe.period) <= 720 ) or
     (_htf == "1W" and str.tonumber(timeframe.period) <= 720 ) or
     (_htf == "1W" and timeframe.isdaily ) or
     (_htf == "1M" and str.tonumber(timeframe.period) <= 720 ) or
     (_htf == "1M" and timeframe.isdaily ) or
     (_htf == "1M" and timeframe.isweekly ) or
     (_htf == "3M" and timeframe.isweekly ) or
     (_htf == "3M" and timeframe.isdaily ) or
     (_htf == "3M" and timeframe.ismonthly ) or     
     (_htf == "3M" and timeframe.period == "240" )
RemainingTime(_TF) =>
    //_TF = timeframe.period
    if barstate.isrealtime
        timeRemaining = (time_close(_TF) - timenow) / 1000
        days = math.floor(timeRemaining / 86400)
        hours = math.floor((timeRemaining - days * 86400) / 3600)
        minutes = math.floor((timeRemaining - days * 86400 - hours * 3600) / 60)
        seconds = math.floor(timeRemaining - days * 86400 - hours * 3600 - minutes * 60)

        r = str.tostring(seconds, '00')
        if minutes == 0
            r:= str.tostring(minutes, '00') + ':' + r
            r
        if minutes > 0 or hours > 0 or days > 0
            r := str.tostring(minutes, '00') + ':' + r
            r
        if hours > 0 or days > 0
            r := str.tostring(hours, '00') + ':' + r
            r
        if days > 0
            r := str.tostring(days) + 'D ' + r
            r
        r

    else
        'Market closed'
///////////////////////////////////////

/////////////////////////////////////////////////////////
var tablo3 = table.new(position = position.bottom_center,columns = 2,rows = 11,frame_color=color.new(color.teal,50),frame_width=2,border_color=color.new(color.teal,50),border_width=1)
if not str.contains(syminfo.tickerid,"replay")and show_rm
    table.cell(tablo3,0,0,text="TF: " + RemainingTime(timeframe.period) ,text_color=color.white,bgcolor= #089981, text_size = i_font)
    table.cell(tablo3,0,1,text=f_text(htf)+" : "+ RemainingTime(htf) ,text_color=color.white,bgcolor= #089981, text_size = i_font)
    
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
h_swept      = h0 > h1 and math.max(o0,c0) < h1 ? true : false
l_swept      = l0 < l1 and math.min(o0,c0) > l1 ? true : false

if timeframe.change(htf)
    h_swept1 := h_swept[1]
    l_swept1 := l_swept[1]